services:
  db:
    image: postgres:15
    container_name: finary-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: finary-redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - '6380:6379'
    volumes:
      - redis-db:/data
    restart: always

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: finary-app
  #   depends_on:
  #     - db
  #     - redis
  #   ports:
  #     - '8000:8000'
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #     - /app/node_modules/.prisma
  #   working_dir: /app
  #   command: sh -c "npx prisma generate && npm run start:dev"
  #   env_file:
  #     - .env
  #   environment:
  #     DB_HOST: db
  #     DB_PORT: 5432
  #     DB_NAME: ${DATABASE_NAME}
  #     DB_USER: ${DATABASE_USER}
  #     DB_PASS: ${DATABASE_PASSWORD}

volumes:
  postgres-data:
  redis-db: